### ISSUE TITLE
No Varnish Example provided

### ISSUE THREAD

**Issue by serhat-ozkara** [uselagoon/lagoon-examples#220]
Hello @tobybellwood ,
https://docs.lagoon.sh/drupal/services/varnish/ links to this repo, for "drupal 8 advanced" it goes to drupal 9 advanced, but there are no example of varnish usage. Also there are no examples of polysite configuration. (with, without varnish)

**Comment by tobybellwood** [comment]
i'll push that back up my to-do list - broadly the Drupal8 version still applies, but last I tried, there were some weird dependency issues around the varnish modules & Drupal9 dependencies. Will dig in and get it out.

Around polysites, we haven't created any specific examples for them, as the only changes are in the .lagoon.yml file (as per the docs https://docs.lagoon.sh/using-lagoon-the-basics/lagoon-yml/#polysite). There are also a few caveats to polysites (one commit triggers all deployments, ability to exercise great control over any single site, and the complexities around the .lagoon.yml file), so we generally advise people to consider carefully whether it's the right choice - it's still better than multisite though :wink:

**Comment by tobybellwood** [comment]
There's now a varnish example at https://github.com/lagoon-examples/drupal9-varnish
